apiVersion: apps/v1
kind: Deployment
metadata:
  name: satisfactory
  labels:
    app: satisfactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: satisfactory
  template:
    metadata:
      labels:
        app: satisfactory
    spec:
      containers:
      - name: satisfactory
        image: wolveix/satisfactory-server:latest
        ports:
        - containerPort: 7777
          hostPort: 7777
          protocol: UDP
        - containerPort: 15000
          hostPort: 15000
          protocol: UDP
        - containerPort: 15777
          hostPort: 15777
          protocol: UDP
        env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: STEAMBETA
          value: "false"
        imagePullPolicy: IfNotPresent
